spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercedb
    username: postgres
    password: mugwadavid

  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true